remote_theme: pages-themes/hacker@v0.2.0
show_downloads: false
title: AIS
description: Promotion 2026
github:
  is_project_page: false
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
